name: Build & Deploy Backend
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: '18' }
      - name: Install deps
        working-directory: backend
        run: npm ci
      - name: Run tests
        working-directory: backend
        run: npm test
      - name: Build
        working-directory: backend
        run: npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name:   your-heroku-app-name
          heroku_email:      you@example.com